name: "run-linting-checks"
on: [push]

jobs:
  run-pylint:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # update stats
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - run: |
          PYLINT_REPORT=$(./run_pylint.sh)
          echo "PYLINT_REPORT<<EOF" >> $GITHUB_ENV
          echo "$PYLINT_REPORT" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
            
      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Run Pylint
          conclusion: ${{ job.status }}
          output: |
            {"summary":"${{job.status}}" , "text_description": "Job has finished"}
          annotations: |
            ${{ env.PYLINT_REPORT }}