name: "run-linting-checks"
on: [push]

jobs:
  run-pylint:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # update stats
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - run: |
          SCRIPT_INIT_HOOK="import sys; sys.path.append('scripts/')"
          echo "PYLINT_REPORT=$(pylint --init-hook=$SCRIPT_INIT_HOOK scripts/*)" >> $GITHUB_ENV
            
      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"${{ steps.test.outputs.summary }}   ${{ env.PYLINT_REPORT}}"}