name: Update data

on:
  [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # update stats
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - run: ./update.sh
        env:
          OAUTH_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
      - run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@users.noreply.github.com'
          git add -A
          timestamp=$(date -u)
          git commit -m "update data: ${timestamp}" || exit 0
          git push
